export const actionType = {
   LOGIN_SUCCESS: 'LOGIN_SUCCESS',
   LOGIN_FAIL: 'LOGIN_FAIL',
   LOGOUT: 'LOGOUT',
   ADD_SUCCESS: 'ADD_SUCCESS',
   ADD_FAIL: 'ADD_FAIL',
   GET_LIMIT: 'GET_LIMIT',
   GET_ALL_ADMIN: 'GET_ALL_ADMIN',
   DELETE_SUCCESS: 'DELETE_SUCCESS',
   DELETE_FAIL: 'DELETE_FAIL',
   GET_ALL_KHOA: 'GET_ALL_KHOA',
   GET_ALL_SINHVIEN: 'GET_ALL_SINHVIEN',
   GET_ALL_MONHOC: 'GET_ALL_MONHOC',
}
