export { default as Header } from './Header'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Nav } from './Nav'
export { default as Contact } from './Contact'
export { default as PaginationSV } from './PaginationSV'
export { default as PaginationMH } from './PaginationMH'
